### ISSUE TITLE
Constructor review 

### ISSUE THREAD

**Issue by Djuki** [nestedminds/resizing-library-risto987#1]
In `ResizeLib` constructor you create image resource and set width and height of the image. Lets see how that looks: 

```
/**
 * Set the image witch you want to resize
 *
 * @param  $imageFile     - path to specific image
 */
function __construct($imageFile)
{
    $this->setImage($imageFile); //method to check and return jpg/gif/png
    $this->width = imagesx($this->image);
    $this->height = imagesy($this->image);
}
private function setImage($imageFile)
{
    // check the image type and get it with GD Library function
    $size = getimagesize($imageFile);
    $this->type = $size['mime'];
     switch($this->type) {
         case 'image/jpg':
         case 'image/jpeg':
             // jpg extension
             $this->image = imagecreatefromjpeg($imageFile);
             break;
         case 'image/gif':
             //for gif extension
             $this->image = imagecreatefromgif($imageFile);
             break;
         case 'image/png':
             //for png extension
             $this->image = imagecreatefrompng($imageFile);
             break;
         default:
             throw new Exception('The file in not an image, tray another file type. ');
             break;
     }
}
```

Image Resize library do not need width and height. That properties belongs to Image. I would remove height and width.

Method: setImage has switch branch which we can avoid. If you look at the library Image WorkShop you can create one layer like this:

```
$pinguLayer = ImageWorkshop::initFromPath(__DIR__.'/../path/to/images/pingu.jpg');
```

That layer will represent the image and he can told you what is the size of the image.

You can pass the image PATH to the constructor and he can set his image layer. That will be good for start. What do you think about this: @risto987

**Comment by risto987** [comment]
@Djuki 
Apparently it seems better and cleaner that way, and when we already use Workshop library why not take advantage of it...
But wen I remove width and height how to use width and height form 
ImageWorkshop::initFromPath,  because that variables is protected?

**Comment by Djuki** [comment]
@risto987 

http://phpimageworkshop.com/doc/2/layer.html

$layer->getWidth(); // in pixel
$layer->getHeight(); // in pixel

**Comment by risto987** [comment]
@Djuki 
I was able to implemented methods from workshop, but still crop method will not work, actually it work but it won't to save correctly, I making a mistake somewhere? Help!
One more question: 
When I initiation method ImageWorkshop::initFromPath($imageFile);
and forward it to the variable protected $workshopLib; 
like this $this->workshopLib = ImageWorkshop::initFromPath($imageFile);
Why do we have to initiation it again in every method, i try to use like this $this->workshop->crop(),
 $this->workshop->crop(),
or I missing something?

**Comment by Djuki** [comment]
@risto987 I don't think that you need to initiate that in every method.

Lets close this one, and than I will open new one with another set of suggestions.
